// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRmDLnNcHX2pBa-dzaN73mqKhewqWF2E',
    appId: '1:507917410892:web:bc4fd19c6051aee3380ae9',
    messagingSenderId: '507917410892',
    projectId: 'belge-siniflandirma',
    authDomain: 'belge-siniflandirma.firebaseapp.com',
    storageBucket: 'belge-siniflandirma.firebasestorage.app',
    measurementId: 'G-2GTN41F6F1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhPZQDfNTyvhG_KL6_-EWaqWpf8ffA61Q',
    appId: '1:507917410892:ios:b17b8e5519a44e0e380ae9',
    messagingSenderId: '507917410892',
    projectId: 'belge-siniflandirma',
    storageBucket: 'belge-siniflandirma.firebasestorage.app',
    iosBundleId: 'com.example.arg30Frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsRmDLnNcHX2pBa-dzaN73mqKhewqWF2E',
    appId: '1:507917410892:web:33cbf357b1fb968a380ae9',
    messagingSenderId: '507917410892',
    projectId: 'belge-siniflandirma',
    authDomain: 'belge-siniflandirma.firebaseapp.com',
    storageBucket: 'belge-siniflandirma.firebasestorage.app',
    measurementId: 'G-KQ72GDYQK7',
  );
}
